name: Python CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Python CI - test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Dependencies
        run: |
          pip install .
          pip install -r tests/requirements.txt
      - name: Lint with flake8
        run: flake8
      - name: Test with Python3 
        working-directory: tests
        run: python3 -m unittest
      - name: Demo dependencies
        working-directory: demo
        run: pip install -r requirements.txt
      - name: Inject dummy example config
        working-directory: demo
        run: printf "[duo]\nclient_id=DIAAAAAAAAAAAAAAAAAA\nclient_secret=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\napi_hostname=example.duosecurity.com\nredirect_uri=http://localhost:8080\nfailmode=closed\n" > ./duo.conf
      - name: Verify flask can load demo
        working-directory: demo
        run: flask routes
